<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anndy-PC" ignored="0" name="Default test" tests="1" failures="1" timestamp="07 八月 2019 10:26:39 GMT" time="0.937" errors="0">
  <testcase name="Demo1" time="0.891" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : expected [true] but found [false] in method : .Demo1(HomeTestCase1:72)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.Demo1(HomeTestCase1.java:72)
]]>
    </failure>
  </testcase> <!-- Demo1 -->
</testsuite> <!-- Default test -->
