<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anndy-PC" ignored="0" name="Test" tests="4" failures="4" timestamp="06 八月 2019 08:25:10 GMT" time="10.816" errors="0">
  <testcase name="case1" time="10.753" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : expected [true] but found [false] in method : .case1(HomeTestCase1:28)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.case1(HomeTestCase1.java:28)
]]>
    </failure>
  </testcase> <!-- case1 -->
  <testcase name="demo1" time="0.004" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : 预期与实际不符合 expected [yy] but found [QQ] in method : .demo1(HomeTestCase1:34)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.demo1(HomeTestCase1.java:34)
]]>
    </failure>
  </testcase> <!-- demo1 -->
  <testcase name="demo2" time="0.003" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : 预期与实际不符合 expected [yy] but found [QQ] in method : .demo2(HomeTestCase1:40)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.demo2(HomeTestCase1.java:40)
]]>
    </failure>
  </testcase> <!-- demo2 -->
  <testcase name="demo3" time="0.002" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : expected [false] but found [true] in method : .demo3(HomeTestCase1:46)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.demo3(HomeTestCase1.java:46)
]]>
    </failure>
  </testcase> <!-- demo3 -->
</testsuite> <!-- Test -->
